// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs7hTfPTknWh_jgiGS6H0rDWSFbV4JU4A',
    appId: '1:467394410651:web:44a1f9150fa574e7f7ee3e',
    messagingSenderId: '467394410651',
    projectId: 'makhzooni',
    authDomain: 'makhzooni.firebaseapp.com',
    storageBucket: 'makhzooni.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlpw6JYB2TWu48eBG97dlVh-_E5PfKhYc',
    appId: '1:467394410651:android:43f723d4f39e35c4f7ee3e',
    messagingSenderId: '467394410651',
    projectId: 'makhzooni',
    storageBucket: 'makhzooni.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP-ltWJGE-E5V1J2jFngVxAxZ_laRYWHw',
    appId: '1:467394410651:ios:9509cf5ff98327e9f7ee3e',
    messagingSenderId: '467394410651',
    projectId: 'makhzooni',
    storageBucket: 'makhzooni.firebasestorage.app',
    iosBundleId: 'com.example.mkhzoni',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCP-ltWJGE-E5V1J2jFngVxAxZ_laRYWHw',
    appId: '1:467394410651:ios:9509cf5ff98327e9f7ee3e',
    messagingSenderId: '467394410651',
    projectId: 'makhzooni',
    storageBucket: 'makhzooni.firebasestorage.app',
    iosBundleId: 'com.example.mkhzoni',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBs7hTfPTknWh_jgiGS6H0rDWSFbV4JU4A',
    appId: '1:467394410651:web:37a70cef9411900cf7ee3e',
    messagingSenderId: '467394410651',
    projectId: 'makhzooni',
    authDomain: 'makhzooni.firebaseapp.com',
    storageBucket: 'makhzooni.firebasestorage.app',
  );
}
