import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import '../../../data/models/product_model.dart';

class AddProductScreen extends StatefulWidget {
  const AddProductScreen({super.key});

    @override
      State<AddProductScreen> createState() => _AddProductScreenState();
      }

      class _AddProductScreenState extends State<AddProductScreen> {
        final _formKey = GlobalKey<FormState>();
          final _nameController = TextEditingController();
            final _priceController = TextEditingController();
              final _quantityController = TextEditingController();

                bool _isLoading = false; // متغير لتتبع حالة التحميل

                  @override
                    void dispose() {
                        _nameController.dispose();
                            _priceController.dispose();
                                _quantityController.dispose();
                                    super.dispose();
                                      }

                                        Future<void> _saveProduct() async {
                                            if (!_formKey.currentState!.validate()) {
                                                  return; // إذا كانت البيانات غير صالحة، لا تكمل
                                                      }

                                                          setState(() {
                                                                _isLoading = true; // بدء التحميل
                                                                    });

                                                                        // تحويل البيانات من الحقول إلى كائن منتج
                                                                            final newProduct = Product(
                                                                                  name: _nameController.text,
                                                                                        price: double.tryParse(_priceController.text) ?? 0.0,
                                                                                              quantity: int.tryParse(_quantityController.text) ?? 0,
                                                                                                  );

                                                                                                      try {
                                                                                                            // الاتصال بـ Firestore وحفظ المنتج
                                                                                                                  await FirebaseFirestore.instance.collection('products').add(newProduct.toMap());

                                                                                                                        // إظهار رسالة نجاح
                                                                                                                              ScaffoldMessenger.of(context).showSnackBar(
                                                                                                                                      const SnackBar(
                                                                                                                                                content: Text('تم حفظ المنتج بنجاح!'),
                                                                                                                                                          backgroundColor: Colors.green,
                                                                                                                                                                  ),
                                                                                                                                                                        );

                                                                                                                                                                              // التحقق من أن الواجهة لا تزال موجودة قبل العودة
                                                                                                                                                                                    if (mounted) {
                                                                                                                                                                                            Navigator.of(context).pop();
                                                                                                                                                                                                  }

                                                                                                                                                                                                      } catch (e) {
                                                                                                                                                                                                            // في حال حدوث خطأ
                                                                                                                                                                                                                  print('حدث خطأ أثناء حفظ المنتج: $e');
                                                                                                                                                                                                                        ScaffoldMessenger.of(context).showSnackBar(
                                                                                                                                                                                                                                SnackBar(
                                                                                                                                                                                                                                          content: Text('حدث خطأ أثناء الحفظ: $e'),
                                                                                                                                                                                                                                                    backgroundColor: Colors.red,
                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                      } finally {
                                                                                                                                                                                                                                                                            // إيقاف التحميل في كل الحالات (نجاح أو فشل)
                                                                                                                                                                                                                                                                                  if (mounted) {
                                                                                                                                                                                                                                                                                          setState(() {
                                                                                                                                                                                                                                                                                                    _isLoading = false;
                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                          @override
                                                                                                                                                                                                                                                                                                                            Widget build(BuildContext context) {
                                                                                                                                                                                                                                                                                                                                return Scaffold(
                                                                                                                                                                                                                                                                                                                                      appBar: AppBar(
                                                                                                                                                                                                                                                                                                                                              title: const Text('إضافة منتج جديد'),
                                                                                                                                                                                                                                                                                                                                                      backgroundColor: Colors.green,
                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                  body: Padding(
                                                                                                                                                                                                                                                                                                                                                                          padding: const EdgeInsets.all(16.0),
                                                                                                                                                                                                                                                                                                                                                                                  child: Form(
                                                                                                                                                                                                                                                                                                                                                                                            key: _formKey,
                                                                                                                                                                                                                                                                                                                                                                                                      child: ListView(
                                                                                                                                                                                                                                                                                                                                                                                                                  children: [
                                                                                                                                                                                                                                                                                                                                                                                                                                TextFormField(
                                                                                                                                                                                                                                                                                                                                                                                                                                                controller: _nameController,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                decoration: const InputDecoration(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  labelText: 'اسم المنتج',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    border: OutlineInputBorder(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      prefixIcon: Icon(Icons.inventory_2),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      validator: (value) => (value == null || value.isEmpty) ? 'الرجاء إدخال اسم المنتج' : null,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const SizedBox(height: 16),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                TextFormField(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                controller: _priceController,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                decoration: const InputDecoration(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  labelText: 'سعر البيع',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    border: OutlineInputBorder(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      prefixIcon: Icon(Icons.attach_money),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      keyboardType: TextInputType.number,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      validator: (value) => (value == null || value.isEmpty) ? 'الرجاء إدخال السعر' : null,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const SizedBox(height: 16),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                TextFormField(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                controller: _quantityController,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                decoration: const InputDecoration(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  labelText: 'الكمية المتوفرة',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    border: OutlineInputBorder(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      prefixIcon: Icon(Icons.format_list_numbered),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      keyboardType: TextInputType.number,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      validator: (value) => (value == null || value.isEmpty) ? 'الرجاء إدخال الكمية' : null,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const SizedBox(height: 32),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // عرض زر التحميل أو زر الحفظ بناءً على حالة _isLoading
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              _isLoading
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ? const Center(child: CircularProgressIndicator())
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  : ElevatedButton.icon(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onPressed: _saveProduct,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              icon: const Icon(Icons.save),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    label: const Text('حفظ المنتج'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          style: ElevatedButton.styleFrom(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  backgroundColor: Colors.green,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          padding: const EdgeInsets.symmetric(vertical: 16),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  textStyle: const TextStyle(fontSize: 18, fontFamily: 'Cairo'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      