import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import '../../../data/models/product_model.dart'; // لاستخدام قالب المنتج
import 'add_product_screen.dart'; // لفتح شاشة الإضافة

class ProductsScreen extends StatefulWidget {
  const ProductsScreen({super.key});

    @override
      State<ProductsScreen> createState() => _ProductsScreenState();
      }

      class _ProductsScreenState extends State<ProductsScreen> {
        // 1. إنشاء Stream لجلب البيانات الحية من Firestore
          final Stream<QuerySnapshot> _productsStream = 
                FirebaseFirestore.instance.collection('products').snapshots();

                  @override
                    Widget build(BuildContext context) {
                        return Scaffold(
                              appBar: AppBar(
                                      title: const Text("المنتجات"),
                                              backgroundColor: Colors.green,
                                                    ),
                                                          // 2. استخدام StreamBuilder لعرض البيانات
                                                                body: StreamBuilder<QuerySnapshot>(
                                                                        stream: _productsStream,
                                                                                builder: (BuildContext context, AsyncSnapshot<QuerySnapshot> snapshot) {
                                                                                          // 3. حالة وجود خطأ
                                                                                                    if (snapshot.hasError) {
                                                                                                                return const Center(child: Text('حدث خطأ ما'));
                                                                                                                          }

                                                                                                                                    // 4. حالة انتظار البيانات
                                                                                                                                              if (snapshot.connectionState == ConnectionState.waiting) {
                                                                                                                                                          return const Center(child: CircularProgressIndicator());
                                                                                                                                                                    }

                                                                                                                                                                              // 5. حالة عدم وجود منتجات
                                                                                                                                                                                        if (snapshot.data!.docs.isEmpty) {
                                                                                                                                                                                                    return const Center(
                                                                                                                                                                                                                  child: Text(
                                                                                                                                                                                                                                  'لا توجد منتجات حتى الآن.\nاضغط على زر + لإضافة أول منتج.',
                                                                                                                                                                                                                                                  textAlign: TextAlign.center,
                                                                                                                                                                                                                                                                  style: TextStyle(fontSize: 18, color: Colors.grey),
                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                // 6. حالة وجود بيانات: عرضها في ListView
                                                                                                                                                                                                                                                                                                                          return ListView(
                                                                                                                                                                                                                                                                                                                                      padding: const EdgeInsets.all(8.0),
                                                                                                                                                                                                                                                                                                                                                  children: snapshot.data!.docs.map((DocumentSnapshot document) {
                                                                                                                                                                                                                                                                                                                                                                // تحويل البيانات إلى كائن منتج
                                                                                                                                                                                                                                                                                                                                                                              Product product = Product.fromFirestore(document as DocumentSnapshot<Map<String, dynamic>>);
                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                          return Card(
                                                                                                                                                                                                                                                                                                                                                                                                                          elevation: 2,
                                                                                                                                                                                                                                                                                                                                                                                                                                          margin: const EdgeInsets.symmetric(vertical: 6),
                                                                                                                                                                                                                                                                                                                                                                                                                                                          child: ListTile(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            leading: CircleAvatar(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                backgroundColor: Colors.green[100],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    child: Text(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          '${product.quantity}',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                style: const TextStyle(fontWeight: FontWeight.bold, color: Colors.green),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        title: Text(product.name, style: const TextStyle(fontWeight: FontWeight.bold)),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          subtitle: Text('السعر: ${product.price} ريال'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            trailing: const Icon(Icons.arrow_forward_ios, size: 16),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onTap: () {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // لاحقاً: يمكن فتح شاشة تفاصيل المنتج أو تعديله
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }).toList(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            floatingActionButton: FloatingActionButton(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onPressed: () {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Navigator.of(context).push(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          MaterialPageRoute(builder: (context) => const AddProductScreen()),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    child: const Icon(Icons.add),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            backgroundColor: Colors.green,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        