                                                                                                                                                                    }

                                                                                                                                                                              // 5. حالة عدم وجود منتجات
   import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import '../../data/models/product_model.dart';
import 'add_product_screen.dart';

// 1. تحويل الشاشة إلى StatefulWidget
class ProductsScreen extends StatefulWidget {
  const ProductsScreen({super.key});

  @override
  State<ProductsScreen> createState() => _ProductsScreenState();
}

class _ProductsScreenState extends State<ProductsScreen> {
  // 2. متغير لتخزين نص البحث
  String _searchQuery = '';

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("المنتجات"),
        backgroundColor: Colors.green,
      ),
      body: Column(
        children: [
          // 3. إضافة حقل البحث
          Padding(
            padding: const EdgeInsets.all(8.0),
            child: TextField(
              onChanged: (value) {
                setState(() {
                  _searchQuery = value.toLowerCase();
                });
              },
              decoration: const InputDecoration(
                labelText: 'ابحث عن منتج...',
                prefixIcon: Icon(Icons.search),
                border: OutlineInputBorder(
                  borderRadius: BorderRadius.all(Radius.circular(10.0)),
                ),
              ),
            ),
          ),
          // 4. استخدام StreamBuilder لعرض البيانات المفلترة
          Expanded(
            child: StreamBuilder<QuerySnapshot>(
              stream: FirebaseFirestore.instance.collection('products').orderBy('name').snapshots(),
              builder: (context, snapshot) {
                if (snapshot.connectionState == ConnectionState.waiting) {
                  return const Center(child: CircularProgressIndicator());
                }
                if (!snapshot.hasData || snapshot.data!.docs.isEmpty) {
                  return const Center(child: Text('لا توجد منتجات مضافة'));
                }

                // --- منطق الفلترة ---
                final allProducts = snapshot.data!.docs;
                final filteredProducts = _searchQuery.isEmpty
                    ? allProducts // إذا كان البحث فارغاً، اعرض كل المنتجات
                    : allProducts.where((doc) {
                        final productName = (doc.data() as Map<String, dynamic>)['name']?.toString().toLowerCase() ?? '';
                        return productName.contains(_searchQuery); // اعرض فقط ما يطابق البحث
                      }).toList();
                
                if (filteredProducts.isEmpty) {
                  return const Center(child: Text('لا توجد نتائج مطابقة للبحث'));
                }

                return ListView.builder(
                  itemCount: filteredProducts.length,
                  itemBuilder: (ctx, index) {
                    final doc = filteredProducts[index];
                    final product = Product.fromMap(
                      doc.data() as Map<String, dynamic>,
                      doc.id,
                    );
                    return Card(
                      margin: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
                      child: ListTile(
                        leading: CircleAvatar(
                          child: Text(product.quantity.toString()),
                        ),
                        title: Text(product.name),
                        subtitle: Text('السعر: ${product.price.toStringAsFixed(0)} ر.ي'),
                        trailing: const Icon(Icons.edit),
                        onTap: () {
                          // لاحقاً: يمكن فتح شاشة تعديل المنتج هنا
                        },
                      ),
                    );
                  },
                );
              },
            ),
          ),
        ],
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          Navigator.of(context).push(
            MaterialPageRoute(builder: (ctx) => const AddProductScreen()),
          );
        },
        child: const Icon(Icons.add),
      ),
    );
  }
}
                                                                                                                                                                                     if (snapshot.data!.docs.isEmpty) {
                                                                                                                                                                                                    return const Center(
                                                                                                                                                                                                                  child: Text(
                                                                                                                                                                                                                                  'لا توجد منتجات حتى الآن.\nاضغط على زر + لإضافة أول منتج.',
                                                                                                                                                                                                                                                  textAlign: TextAlign.center,
                                                                                                                                                                                                                                                                  style: TextStyle(fontSize: 18, color: Colors.grey),
                                                                                                                                                                                                                                                                                ),
                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                // 6. حالة وجود بيانات: عرضها في ListView
                                                                                                                                                                                                                                                                                                                          return ListView(
                                                                                                                                                                                                                                                                                                                                      padding: const EdgeInsets.all(8.0),
                                                                                                                                                                                                                                                                                                                                                  children: snapshot.data!.docs.map((DocumentSnapshot document) {
                                                                                                                                                                                                                                                                                                                                                                // تحويل البيانات إلى كائن منتج
                                                                                                                                                                                                                                                                                                                                                                              Product product = Product.fromFirestore(document as DocumentSnapshot<Map<String, dynamic>>);
                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                          return Card(
                                                                                                                                                                                                                                                                                                                                                                                                                          elevation: 2,
                                                                                                                                                                                                                                                                                                                                                                                                                                          margin: const EdgeInsets.symmetric(vertical: 6),
                                                                                                                                                                                                                                                                                                                                                                                                                                                          child: ListTile(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            leading: CircleAvatar(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                backgroundColor: Colors.green[100],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    child: Text(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          '${product.quantity}',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                style: const TextStyle(fontWeight: FontWeight.bold, color: Colors.green),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        title: Text(product.name, style: const TextStyle(fontWeight: FontWeight.bold)),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          subtitle: Text('السعر: ${product.price} ريال'),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            trailing: const Icon(Icons.arrow_forward_ios, size: 16),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onTap: () {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // لاحقاً: يمكن فتح شاشة تفاصيل المنتج أو تعديله
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }).toList(),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            floatingActionButton: FloatingActionButton(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    onPressed: () {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Navigator.of(context).push(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          MaterialPageRoute(builder: (context) => const AddProductScreen()),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    child: const Icon(Icons.add),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            backgroundColor: Colors.green,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
