import 'package:flutter/material.dart';

class HomeScreen extends StatelessWidget {
  const HomeScreen({super.key});

    @override
      Widget build(BuildContext context) {
          return Scaffold(
                appBar: AppBar(
                        title: const Text("مخزوني"),
                                backgroundColor: Colors.green,
                                        centerTitle: true,
                                              ),
                                                    body: Padding(
                                                            padding: const EdgeInsets.all(18.0),
                                                                    child: Column(
                                                                              children: [
                                                                                          Card(
                                                                                                        elevation: 2,
                                                                                                                      child: ListTile(
                                                                                                                                      leading: const Icon(Icons.inventory, color: Colors.green),
                                                                                                                                                      title: const Text('إحصائيات سريعة'),
                                                                                                                                                                      subtitle: const Text('المبيعات اليوم: 0 | المنتجات المنخفضة: 0'),
                                                                                                                                                                                    ),
                                                                                                                                                                                                ),
                                                                                                                                                                                                            const SizedBox(height: 16),
                                                                                                                                                                                                                        Expanded(
                                                                                                                                                                                                                                      child: Center(
                                                                                                                                                                                                                                                      child: Column(
                                                                                                                                                                                                                                                                        mainAxisAlignment: MainAxisAlignment.center,
                                                                                                                                                                                                                                                                                          children: const [
                                                                                                                                                                                                                                                                                                              Text(
                                                                                                                                                                                                                                                                                                                                    "مرحبًا بك في مخزوني 💼",
                                                                                                                                                                                                                                                                                                                                                          style: TextStyle(fontSize: 22, fontWeight: FontWeight.bold),
                                                                                                                                                                                                                                                                                                                                                                              ),
                                                                                                                                                                                                                                                                                                                                                                                                  SizedBox(height: 10),
                                                                                                                                                                                                                                                                                                                                                                                                                      Text("إدارة مخزونك وراحتك في جيبك"),
                                                                                                                                                                                                                                                                                                                                                                                                                                          SizedBox(height: 30),
                                                                                                                                                                                                                                                                                                                                                                                                                                                              Text("✨ برمجة وتطوير: النبراس البعداني (Alnbras Albadani)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      style: TextStyle(color: Colors.grey)),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const SizedBox(height: 8),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const Text("Made with ❤️ by النبراس البعداني — Phone: +967-XXXXXXXXX — Email: alnbras.dev@gmail.com",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          textAlign: TextAlign.center,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          style: TextStyle(fontSize: 12, color: Colors.black54)),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }