name: Build Flutter Android APK

on:
  push:
    branches:
      - main

jobs:
  build_apk:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # نكتب المسار الكامل والصريح هنا
      - name: Create Firebase Options file
        env:
          FIREBASE_OPTIONS_CONTENT: ${{ secrets.FIREBASE_OPTIONS }}
        run: echo "$FIREBASE_OPTIONS_CONTENT" > mkhzoni/lib/firebase_options.dart

      # ندخل إلى المجلد ثم ننفذ الأمر
      - name: Install dependencies
        run: cd mkhzoni && flutter pub get

      # ندخل إلى المجلد ثم ننفذ الأمر
      - name: Build APK
        run: cd mkhzoni && flutter build apk --release

      # نستخدم المسار الكامل والصريح هنا
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: makhzoni-app-release.apk
          path: mkhzoni/build/app/outputs/apk/release/app-release.apk
