name: Build Flutter Android APK

on:
  push:
    branches:
      - main

jobs:
  build_apk:
    runs-on: ubuntu-latest
    
    steps:
      # 1. جلب الكود من المستودع
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. تثبيت Java Development Kit (JDK) وهو ضروري لبناء تطبيقات أندرويد
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17' # فلاتر يتطلب نسخة حديثة من جافا

      # 3. تثبيت Flutter SDK
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # 4. إنشاء ملف firebase_options.dart من الأسرار (Secrets)
      - name: Create Firebase Options file
        env:
          FIREBASE_OPTIONS_CONTENT: ${{ secrets.FIREBASE_OPTIONS }}
        run: echo "$FIREBASE_OPTIONS_CONTENT" > mkhzoni/lib/firebase_options.dart

      # 5. تثبيت حزم واعتماديات المشروع
      - name: Install dependencies
        run: cd mkhzoni && flutter pub get

      # 6. بناء ملف الـ APK
      - name: Build APK
        run: cd mkhzoni && flutter build apk --release

      # 7. رفع ملف الـ APK الناتج كـ "Artifact"
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: makhzoni-app-release.apk
          path: mkhzoni/build/app/outputs/flutter-apk/app-release.apk
